name: build
on: [push]
jobs:
  amd64:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install builder
        run: sudo bash build-in-lxd.sh install-builder
      - name: Start builder
        run: sudo bash build-in-lxd.sh start-builder
      - name: Build
        run: sudo bash build-in-lxd.sh build
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: amd64
          path: |
            *.iso
  arm64:
    # NB this uses a self-host runner managed by https://github.com/rgl/lxd-github-actions-runner
    runs-on:
      - self-hosted
      - debian-11
      - arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        shell: sudo bash {0}
        run: |
          set -euxo pipefail
          echo quiet=on >~/.wgetrc
          export DEBIAN_MIRROR=http://ftp.nl.debian.org/debian/
          export LB_BUILD_ARCH=arm64
          bash build.sh
          mv osie-$LB_BUILD_ARCH/live-image-$LB_BUILD_ARCH.hybrid.iso tinkerbell-debian-osie-$LB_BUILD_ARCH.iso
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: arm64
          path: |
            *.iso
  release:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-20.04
    needs:
      - amd64
      - arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download artifacts
        uses: actions/download-artifact@v2
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'amd64/*.iso,arm64/*.iso'
          token: ${{ secrets.GITHUB_TOKEN }}
